### PR TITLE
Formatted the project so that it's installable with pip

### PR DESCRIPTION
**Pull request by Jorgvt**
Hi!
We were trying to use this module in class but couldn't make it work through the usual git clone and pip install procedure so I reviewed the project and saw that it was missing a setup.py file to make that possible. I imagine it's not needed to actually use the module, but with these changes we could use it easily in class and I thought you may wanted to check it out. I wanted to open an issue but couldn't figure out how, so I made a pull request, sorry if it bothers you.

Also I added a usage example done in Colab.

### CODE REVIEW

**Comment by Jorgvt** [comment]
@googlebot I signed it!

**Comment by jonycgn** [comment]
Hey, thanks for this contribution! This is very nice. This repository is synced with an internal (non-git) repository at Google, so unfortunately I can’t just accept the PR, because it would bring the synchronization out of whack. It will need a bit more work to integrate it so that everything works. I’ll look into it!

**Comment by Jorgvt** [comment]
Thanks for your quick response! Im so glad you found it nice.
Should I close the PR then?

**Comment by jonycgn** [comment]
No, please keep it open. It is a good reminder. Perhaps I can get PRs to work.

**Comment by jonycgn** [comment]
Hi, thanks again for your input! I ended up formatting things a bit differently, but now it should be possible to install this via pip (see README for command line). Closing this PR since it is not needed any more.

**Pull request closed without merging**
